#pragma once

#include "../System/RandomGen.h"

namespace NGameX
{
  namespace RandomNicknameHelper
  {
    // Массив случайных имён для игроков
    static const wchar_t* const RANDOM_NICKNAMES[] = {
        L"Vania219832",
        L"ШиzZza",
        L"Kigagar",
        L"лишённая души",
        L"Brusk",
        L"РАй тик",
        L"Y6EUMEN9NEJNOOOOOOOOO:)",
        L"dop`ing",
        L"TBou_aHreJlo4ek",
        L"-==pro58==-",
        L"n1^mySelf.nO.Skill?",
        L"Pedar",
        L"MC.Додик",
        L"Joelle",
        L"TTpoTuB_Jloma_Hukak",
        L"DiMi4",
        L"nAnKA",
        L"WESTKZ_tm_Dosmagambetov",
        L"6JIaTHou'",
        L"salviamaria",
        L"Kushaju-Plombir",
        L"Fauzahn",
        L"Жизнепоглатитель",
        L"Tembl4",
        L"Blueray",
        L"NaL1m036yp9ITu9I",
        L"Baldon",
        L"JEREMY",
        L"кот дьявола",
        L"Кусочек сыра с паштетом**",
        L"Vertyxan",
        L"Оближи_меня",
        L"CoK_CAHEK",
        L"бауди на ауди",
        L"Темный повелитель чебураторов",
        L"Evil_Cot",
        L"**(-_)KEKC161RUS",
        L"MEETSATANA.YOURMAKER!",
        L"MANTISStRikE-Back",
        L"Brein",
        L"YEEZUS",
        L"Warpath",
        L"frozepro:LeshQaaa",
        L"OREJl",
        L"OTANO",
        L"yxoIop",
        L"unamed",
        L"Dut",
        L"RealSteel|VaMpiR(cl)",
        L"O6KOJIOTblU",
        L"Adriezan",
        L"Паук_Шнюк",
        L"Mann",
        L"Я не идиальная зато реальна",
        L"CrazyMakaroshka",
        L"Tantil",
        L"Frostfont",
        L"я_не_трус_но_я_боюсь",
        L"Dalara",
        L"JlyTTorJla3blu_MaJlb4yraH",
        L"TblyMepoTAWP",
        L"HepeaJlbHo_BeceJla9l",
        L"Displases",
        L"X.B.C.BouH",
        L"o1d_gun",
        L"change_name",
        L"NGKsilvia#2",
        L"Дядя из министерства добрых дел",
        L"SudaNeSmotri",
        L"Faerr",
        L"pro*UKR*CSGUREY",
        L"Mezilrajas",
        L"InComofKillers|Ane4ka",
        L"Не_ежык_но_в_тумане",
        L"Cepblu_kapDuHaJlb4uk",
        L"̶В̶л̶ю̶б̶и̶л̶а̶с̶ь ̶з̶р̶я…",
        L"Mr.Pumba",
        L"СантаШляуз",
        L"in100gramm",
        L"L.B.3JIy4ka",
        L"Тодео",
        L"BpeM9I_TaIILuTb",
        L"_от_А(да)_до_(ра)Я_­",
        L"6am6y4a",
        L"Hu_xpeHa_ce",
        L"SHOKYALL:)@!",
        L"Okie",
        L"Белый нигер",
        L"Девственная извращенка",
        L"korolevhmaravoz",
        L"PuCKHu_CBOEu_KOPMOu",
        L"Печень Сталина",
        L"Abdin",
        L"♡˜”°•T❍λьΚ☉ τβ☉я•°”˜♡",
        L"Лесник",
        L"Macho",
        L"UsedPornoStar",
        L"LLI_K_O_JI_b_H_U_K",
        L"Ķ|/|М_|-|Å_5_Ç_+",
        L"RESPECTALM@TY",
        L"PB_Master",
        L"Yasha888",
        L"Бессмертная_Бестия",
        L"Arlana",
        L"ScHokK",
        L"Ромашка_Бегемотовна",
        L"Mr_KiLLaURa",
        L"barmalei",
        L"Talkree",
        L"oTMorozsko",
        L"CmeTanoKa",
        L"anh1m",
        L"Ďē®зkǻƳǻ",
        L"Во МнЕ ЖиВёТ ÃŇĞĔĽ",
        L"Robin_van_Persie",
        L"V1[m]eR",
        L"GFFFF",
        L"nagibator.",
        L"OnAsНыЙ_TroLL",
        L"mozila",
        L"Tetilar",
        L"зло_в_воплощении_ангела",
        L"XYDO|HUKO",
        L"MucTeP_6uH_3a_PyJIeM",
        L"Kroccuk",
        L"s3rgy",
        L"AsTeRiX",
        L"PaKoB_PaKoM",
        L"Ironfire",
        L"Egorka_nt",
        L"3JIbIe ТеFteLi",
        L"IuBOTHOE",
        L"FL1pSTaR",
        L"Помыла Андерсон",
        L"X_AIS_X",
        L"Aralhala",
        L"Xo4y_Bce_u_cpa3y",
        L"XygoIHuK",
        L"Cotrell",
        L"cheK^",
        L"MecTHblu_XyJluraHuLLIka",
        L"Ya_B0G_A_Tb)_Lo}{",
        L"HE_BE3ET_MHE_COBCEM",
        L"Flake*",
        L"Pooh.Pooh.>Head>Aim!?",
        L"KrIkE",
        L"Перловая каша супер мутант",
        L"Дама без собачки",
        L"KoShAk",
        L"Ho4Hou_BoJl4apa",
        L"Bloodsmith",
        L"TimeDust",
        L"z@bal!__________o_O",
        L"подростковая_тупость",
        L"$KYpidar",
        L"_Lucifer_",
        L"KocMu4eckuu_DpakoH",
        L"Meeds",
        L"Dark Leo",
        L"Aralanim",
        L"Mr.santa",
        L"RnDOtmorozok",
        L"MaximumV2",
        L"Под испанским нЁбом",
        L"Shayrma_2014",
        L"Milka",
        L"Shift_Lolka_pro>>",
        L"L9|PKa",
        L"@-11-@",
        L"Яичница с беконом",
        L"@Dron@",
        L"w1knd*",
        L"Striptizer",
        L"Sazshura",
        L"**BEKA_KZ***",
        L"Я королева,а вы простите кто?",
        L"афлЁный кирпич",
        L"Demon-Best",
        L"Ferr",
        L"Mohito",
        L"MassiveDynamic",
        L"BM9COLsB|3aBDB!",
        L"finklousen",
        L"Morann",
        L"withlovefromekbkot3_awp_pro",
        L"MaJleHbka9l_TTpuHLjecca",
        L"Arashigore",
        L"Farria",
        L"NoooB",
        L"StaRs",
        L"heidaro",
        L"ilyas",
        L"Ruthven",
        L"MicRoBooM",
        L"OTkpblTa9l_DyLLla",
        L"BOT_BLIN!",
        L"MrCraft",
        L"Bella",
        L"Air-PRO",
        L"NIGGA_KillER",
        L"lllkoJIbHuk_kak_EHOT",
        L"Fenrikinos",
        L"dobro",
        L"Fezragore",
        L"ФСБ_постучись",
        L"ЦойЖив",
        L"C.t.y.g.e.n.t.*.*.",
        L"co3DaHa_DJI9I_JII-06Bu",
        L"ŦI_ŔEĶŠ",
        L"Пирожок-братан булочки",
        L"FrizYT",
        L"EnderGuy",
        L"Fate",
        L"RenDikS",
        L"piazon",
        L"KopoJleBa_Be4epa",
        L"Гибрид оленя с человелом",
        L"Egor_6e3_TpycoB_NaGiBaeT",
        L"wawlik",
        L"Ha_KoJIeHu_OJIeHu",
        L"Ежик на скутере",
        L"BaJIePkA",
        L"llDLzllMr.VOLT",
        L"ЛеНиН ЖиВ",
        L"THE BLOODY KNIGHT",
        L"Mast",
        L"CTAJIuH",
        L"3a4em!?",
        L"3JIbIe_Tanku",
        L"Apocalypse",
        L"TaPo4oK",
        L"MULTIK",
        L"Mcclard",
        L"kot3_awp_pro",
        L"llDLzll",
        L"Mr.VOLT",
        L"Drelazar",
        L"Moriel",
        L"Zulabar",
        L"BoBa_B_Tpycax",
        L"Hunky",
        L"MaJlo_BpeMeHu",
        L"Gardarg",
        L"9I_rAMHO_2",
        L"С.Т.А.Р.Ы.Й. Б.Е.З.У.М.Е.Ц.",
        L"Fehuginn",
        L"Mr.LOLKA",
        L"400kg.",
        L"Gently",
        L"Karin",
        L"Магнус",
        L"ТуФлЁй_По_ЯйЦаМ",
        L"Kto_sper_mou_nik",
        L"AH7EJI_IIPEgOXPAHuTEJIb",
        L"ПуЛи_От_ДеДуЛи",
        L"TpeuDep",
        L"BAXBAXIMIMO!",
        L"Cristiano_Ronaldo",
        L"Parakon",
        L"sosiska",
        L"CHESTER",
        L"Namatrasnik",
        L"nekit",
        L"D.Drogba",
        L"Kreelan",
        L"4000kg",
        L"Бугагашенька",
        L"TonyMantana",
        L"shinobi",
        L"Akinozilkree",
        L"~GHo_OSTc.Undefeated.tmnakyr",
        L"YanFox",
        L"4е_Za_FIGniA",
        L"Balak",
        L"Mazilkree",
        L"-k0FFe-",
        L"Djoker",
        L"Мировой Пельмень",
        L"Sharpweaver",
        L"AW_BUTLER",
        L"XpoMocoMa",
        L"Kagarn",
        L"Многокашиел",
        L"Clarine",
        L"Бум",
        L"ThePro",
        L"Старики кактусы смерти",
        L"Stoneworker",
        L"dimon2013",
        L"OldSchool",
        L"D1amondL1on",
        L"MAGNUM`''",
        L"Veruyuschiy_Ateist",
        L"✞Ã₣ℛǾÐĬŤẵ✞",
        L"Bandinaya",
        L"CEKPET",
        L"Cebor",
        L"KuKu_T_T_KuKu",
        L"One_Shot_pro",
        L"fAStt,",
        L"Dam_20_santim",
        L"BafJl9l_TawuT_uHfaCoTka",
        L"Нюх",
        L"Megor",
        L"hs.top#1.",
        L"KoBapHblu_PoMaHTuk",
        L"A.P.O.K.A.L.1.P..1..",
        L"Fusion-Jamp",
        L"Truthdragon",
        L"Pea/IHbIu4e/I",
        L"oTeu_kpecTHblu",
        L"Mr.Proper",
        L"TTpocTa9l_Taka9l",
        L"AntIS",
        L"zidaneew",
        L"Bearus",
        L"seksualnayaagressia",
        L"ОпА$нЫй_ВоЗрА$т",
        L"4yJIo4ku_B_ceTo4ky",
        L"BORI67RUS",
        L"Rushenberg",
        L"destrOFFik",
        L"эхо унитазного бачка",
        L"ВЫЛЫСЫПЫДЫСТ",
        L"GamerT",
        L"Dela.k.aLeTruk",
        L"pechenyha",
        L"Соса_Со1а_2.0",
        L"Aleks.rid",
        L"Xyk_cJIeBa_28RUS",
        L"Cherry The Countess",
        L"No-MyAC```maorri```",
        L"страусятина",
        L"Logan_Present",
        L"Max1E",
        L"luchshe_vsekh",
        L"Arabella V.",
        L"Maxatrom",
        L"Hu_4e_ce",
        L"Remsi",
        L"Lady_in_Red",
        L"Flamesong",
        L"Best Play",
        L"CypoBblu_MaJlb4yraH",
        L"Alverta",
        L"Salkree",
        L"Mo}{natbIe SI’LLa",
        L"killednormgameraheadshotfr",
        L"Nickname Master",
        L"Cashoutmaster",
        L"Vitaminka",
        L"ykol_v_popy",
        L"MedveDb",
        L"XJle6o6yJlo4HoE_UzDeJluE",
        L"Нудистка",
        L"Хранительница чешки",
        L"moUFE",
        L"Ни разу не критовик!",
        L"ZhanBratan",
        L"RB18+>>",
        L"ndup",
        L"Вечно молодой",
        L"НОЧНОЙ_ПОРТНОЙ",
        L"Elthins Horde",
        L"Bloodray",
        L"Denisonchik",
        L"Злая тарелка",
        L"JIeBblu_HoCoK",
        L"CJlaDkuu_caxapok",
        L"TuTaHuk_Ha_TTJlaBy",
        L"Black.__.Star",
        L"OtdelK",
        L"TeSkooO!",
        L"LuckyDay",
        L"CaJlo_CuJla_CnoPT_MoruJla",
        L"HauTu_u_TTepenp9lTaTb",
        L"Nezameten",
        L"Яубьютогоктосломалм­ойпробел",
        L"MAMASTIFLERA",
        L"Fatalik",
        L"cheLentano",
        L"lAngelMaestre###l",
        L"BTeMe|Dog:)",
        L"sKyrEEd",
        L"JlackoBa9l_koLLle4ka",
        L"adv`aks0n",
        L"by'N1ceg1RLw1Thawp!",
        L"ZVER07",
        L"Святой Блинчик",
        L"_LegenDa_",
        L"Anarasius",
        L"The_Best_CyX_Wolf",
        L"RostyslavK.",
        L"Diggern",
        L"Fordregda",
        L"Fekree",
        L"He_oTBe4au_MHe",
        L"Пьяная Мартышка",
        L"BupTyaJlbHa9l_4epToBka",
        L"Agagamand",
        L"KWGSensei",
        L"SpayntHunter",
        L"Ведро с глазами",
        L"~_Saxons_~",
        L"Elwood",
        L"~L!keStr1ke",
        L"MAKAPOHA_B_TPYCAX",
        L"O4eHb_BpeDHa9l",
        L"хрен в каске2",
        L"PBAHbIE_TPYCbI",
        L"Nameena",
        L"Lamer",
        L"2Unlimited",
        L"Pulqk@",
        L"HE_BE3ET_MHE_",
        L"Волшебные репетузы",
        L"Гравицапа",
        L"Frostbool",
        L"5fggh",
        L"Сытый тролль",
        L"yMHblu_kyJlbTypucT",
        L"hitman",
        L"LEPS_6E3_TPYCOB",
        L"Painkiller",
        L"CaMa9l_3a6aBHa9l",
        L"Ironfont",
        L"***polevkoy***",
        L"FDGOD",
        L"грязь из под ногтей",
        L"TTaJlo4ka_Bblpy4aJlo4ka",
        L"Diman007",
        L"SnoxJ",
        L"OJIiMIIiK",
        L"Fulula",
        L"Katilar",
        L"BillyMilligan",
        L"kristinka",
        L"SkyPipe",
        L"AryTuH66(ekb)",
        L"ABToMaT_kaJlaLLlHukoBa",
        L"PrincPersia",
        L"PoMaHTu4Ha9l",
        L"OldbuddyFlint",
        L"Tami",
        L"cJIa6ak",
        L"pravosleva",
        L"Mpa4HoBaTblu_4eJl",
        L"Alsa",
        L"Фипилявая какаФка",
        L".::IIo3uTuB4uK::.",
        L"webm@ster",
        L"VITAS",
        L"DJ_HEAD--",
        L"kst6ap6ocuk",
        L"eX.Virus>3eBaka",
        L"Forceshaper",
        L"C_BepTyXu_B_YxO_TOPTuKy",
        L"CyTTep_yJlbl6ka",
        L"BHe_ToJlTTbl",
        L"Гейм овер",
        L"Cristobal",
        L"6aPa6aXa",
        L"Мертвая дельфинка",
        L"AkuLA",
        L"maN1aK x_O",
        L"Хрум-Хрумыч",
        L"Kak_cTepBa_uHorDa",
        L"S4astliviipapa",
        L"Фрекен Бог",
        L"простой парень с Рублёвки...",
        L"Kak_xo4y_Tak_u_kpy4y",
        L"~S.W.A.G.~Lida.by",
        L"hoochiemama",
        L"врач-похметолог",
        L"Bucket",
        L"Очкастый мачо",
        L"KoMyHucT_u3_cu6upu",
        L"Karisar",
        L"Kari",
        L"Buzalbine",
        L"mXn",
        L"SPAWNE6AW1448",
        L"Ariginn",
        L"Скупщик ресниц",
        L"визуальный обман",
        L"Reidhaar",
        L"6eccTpaLLIHblu_noHu_228",
        L"smerch",
        L"Borus",
        L"3Jla9l_6ecTu9l",
        L".:Dom1no:.",
        L"Corine",
        L"Mist @@@",
        L"Iwannabeamonster",
        L"Dante",
        L"Hi_Jacker",
        L"ch0tkin",
        L"f0sterwOw",
        L"Hakypu_KoTа",
        L"Мертвый Котенок",
        L"Tatanaka",
        L"† КОЛХОЗНИК †",
        L"Ironsmasher",
        L"PILOT",
        L"milawka",
        L"leprikon",
        L"starik",
        L"Castagnier",
        L"Drova1990",
        L"6yrop",
        L"betHOven",
        L"GERMAN_nikopol_ua",
        L"TIpuBblkJla_BepuTb",
        L"Про100cookie",
        L"Getto",
        L"омлетка+)",
        L"sanekk192",
        L"Laflen",
        L"Йожик_без_кое-чего",
        L"terroristka и fsbshnica",
        L"Nall",
        L"Jugami",
        L"Disbalance",
        L"kakadu73",
        L"T2KM_BLR!",
        L"Und3rgr0undSedyga",
        L"Dobriy Govnodaw",
        L"Невеста ветра",
        L"Daisho",
        L"0ssTraSI Ko4erbI}|{kA",
        L"BepuTb_B_4yВo",
        L"ZzMaster",
        L"БеШаНаЯ НоГа",
        L"**(-_)YKROP161RUS",
        L"VALTHER",
        L"NA'VImarkeloff/A/",
        L"ekbAndrey",
        L"kakTak?",
        L"BoЗbMy B РoT 3a 6yTEP6poT",
        L"StRaX",
        L"Ballarne",
        L"4ikapuk",
        L"Razdalbaika",
        L"brainfucker",
        L"Sall",
        L"GribOK!!!",
        L"стрЁмный физрук",
        L"TPACEP",
        L"Kiri",
        L"XYLIGAN",
        L"Али Ибн Абдул Обстул Бей",
        L"Sky",
        L"Bloodfire",
        L"Lightfire",
        L"Ятидренный Хряп",
        L"Shalirus",
        L"То яма то канава - Монк",
        L"появилась из облака",
        L"caM_Tbl_Dypak",
        L"}{a|{eR_MaZaFa|{eR",
        L"KYRGYZSTANRULIT",
        L"Ma4eTeHeCMCut!",
        L"Blanshed",
        L"Гербалайф",
        L"Фризер",
        L"7futovpodkilem,yo-xo-xo",
        L"Kasper",
        L"professor_sosiskin",
        L"Чучело-Мяучело",
        L"Squeeze",
        L"The(Best)olo4b",
        L"top1|NasteN'ka",
        L"Allure",
        L"GAD777",
        L"девчонка в наушниках",
        L"9 6erу TAkou a BoJIocbI Ha3ad",
        L"Landardin",
        L"naemnik",
        L"|ReD-TowN|-aibek",
        L"Bubandis",
        L"TBo9l_Me4Ta_HaBcerDa",
        L"ОчЕнЬ ЧуЖоЙ",
        L"4yDuk!!!",
        L"Adrielar",
        L"MaxWell",
        L"SkilloT6ora",
        L"NaGiBatoR",
        L"Dimon_Ukr",
        L"MeXaHuK",
        L"KaRTeL999",
        L"cMepTHuk",
        L"xander",
        L"kennuss)VSMIX",
        L"Katharina",
        L"シγλыδнμςьツ",
        L"100pudoff",
        L"wkepatm|Deniska",
        L"venom",
        L"Loading....",
        L"сумасшедший автобус",
        L"NoName",
        L"villa7",
        L"Vikasa",
        L"anti",
        L"Матраскин",
        L"ВеЛиКиЙ КуКуРуЗкО",
        L"Adoth",
        L"IIpo100NOOB:DD",
        L"-=D.i.C=-",
        L"Водаврот",
        L"JEDAY",
        L"Димка вырви глаз",
        L"Хип-Хоп в Твоём Доме",
        L"Пих Пах Убит Нах",
        L"kpoJluk_c_yxaMu",
        L"XyJIuraHo4ka",
        L"zeon",
        L"МиСс НеПрИяТнОсТь",
        L"Psylocibin",
        L"Шо_тЫ_ВИЛУПIЛОСЬ??!­",
        L"FaPToBbIu",
        L"Fern",
        L"Jerry",
        L"LOLOLOWKA",
        L"Po3oBblu_PoMaHTuk",
        L"kostya118",
        L"Galar",
        L"90x60x90",
        L"*kpyTou*TuII*Turbo",
        L"Thetalmeena",
        L"diman",
        L"belka_bez_TpycoB",
        L"Gholbirad",
        L"JloBe_Ha_kapMaHe",
        L"MoNCTRIk",
        L"BlackSabbath",
        L"Battleship#lCaptainMorganl",
        L"Ornellas",
        L"Grojin",
        L"Malanrad",
        L"Девчонка без тормозов",
        L"GrehN!K",
        L"Gavinramath",
        L"Mandarin4ik",
        L"Пернатый Перфоратор",
        L"Hard+",
        L"Katya",
        L"кукла дождя",
        L"Бухое печенюшко",
        L"Lester",
        L"Battery",
        L"Janell",
        L"4emodan",
        L"wini*Saint-Petersburg",
        L"Auririn",
        L"_sanekak47_",
        L"Smail",
        L"Maverig",
        L"MrDruddeGames",
        L"KOHAHBAPBAP'#3",
        L"iron warrior",
        L"Loading… ██████████████] 99%",
        L"Butcher",
        L"Dj хлопушка",
        L"Najinn",
        L"the wing of life",
        L"Buzaron",
        L"Hugo_borz",
        L"Frostfist",
        L"Abywis",
        L"BilzpupsLoL",
        L"CJlaDka9l_kak_caxap",
        L"seletka",
        L"В о л ч и ц а",
        L"тяжелое пёрышко",
        L"ღღღ₵√℮Ⱡⱥღღღ",
        L"CGClKaTePuHKa*",
        L"pluto",
        L"Sweetheart",
        L"Balladodwyn",
        L"ьькосмический калощьь",
        L"-=Den4uK=-",
        L"Pycckuu_TIaTpuoT",
        L"ZlodeY_Na_TankE",
        L"F2playDuMBaSS**",
        L"roJloBoJloMo4ka",
        L"Ficarra",
        L"@*****PRIZROK*****@",
        L"Грегуар на трахуаре",
        L"SSERZZ",
        L"romka",
        L"Mr.Green",
        L"папа антилопы",
        L"CMoTpu_u_3aBuDyu",
        L"RB18+>Sashen`ka#",
        L"CJlagocTpacTHa9l",
        L"PokoBa9l_kpacaBuLja",
        L"Янот_ЧеРеЗ*Я*",
        L"BJIacTeJIuH",
        L"molokoskrov'u",
        L"?whatthefuck.",
        L"He_BpeDHo_Me4TaTb",
        L"BupTyaJlbHblu_BouH",
        L"Yozil",
        L"Spayke",
        L"Apple_Ѽ_Xrym",
        L"company_THE_Best",
        L"YuSuP",
        L"gg.ZhlStas",
        L"fnatic.f0restSteelSeries",
        L"Toretto145",
        L"pro100(*zLoY*)_(*gAmOrA*):D",
        L"СрульНафсех",
        L"Кпсс-сс",
        L"COBECTb_KOTA",
        L"JleTHuu_BeTepo4ek",
        L"морозоустойчивая дама",
        L"Призрак Ваньки Хоя",
        L"Starweaver",
        L"Jesica",
        L"Душа больна ?",
        L"MePTBbIu_CJIoHuK",
        L"@@@____________@@@",
        L"orHu_ropoDa",
        L"Tygolar",
        L"MopDa_kupTTu4eM",
        L"GeFest",
        L"виртуальная сопля",
        L"Bakypat",
        L"Страшный симпатяга",
        L"SerkinMen",
        L"REDEMAX",
        L"Ko3o4ka_c_poraMu",
        L"Атцкий киви",
        L"Утро псового лая",
        L"Kintus",
        L"TToBapeLLlkuHa",
        L"SUPERCHEL",
        L"Kiss Ме в|слепую",
        L"sw1tch",
        L"просто глюк",
        L"Xa-Xa-Crazy-Xa-Xa",
        L"DoTER*_*228_Pro",
        L"Baramar",
        L"ДЕРЕВОЛАЗ",
        L"Dizahn",
        L"KoBrA(A.N.K)",
        L"Эßøłюция",
        L"fReZeee",
        L"3oHTukoM_ykoJlb4uk",
        L"Идеальная Оптимистка",
        L"Чьи трусы?",
        L"Mr.Go_Od",
        L"Kuшe4нo-Пoлoвoй Tpaкт",
        L"irisSska",
        L"Flamedweller",
        L"IvanGlizalne:ivanglizalne.com",
        L"крик урагана",
        L"stopE!",
        L"molodoy_i_pianbIi",
        L"WOGY",
        L"mahach",
        L"Оператор отбойного молотка",
        L"JoJosida",
        L"Blackstalker",
        L"bulzavr",
        L"xom9k",
        L"tw1x^zz1^aced1v1",
        L"WaSbTePiZdA",
        L"Jester",
        L"Andrey_78RUS",
        L"JleTHuu_BeTepok",
        L"CSFF_OD_UA",
        L"killer",
        L"ChuCk.NoRriSss...././..",
        L"Deshazior",
        L"HowlClaw",
        L"|TOSHIBA|",
        L"nooooooooB+++++++",
        L"ONYX(TROESCHINA",
        L"Советы_рвут_рандом",
        L"CnAc10__MuP",
        L"}{уLiG@No4_kA",
        L"Niga_TV",
        L"Sharks|Velikaya",
        L"Spellsong",
        L"Кровавое Утро",
        L"Pokep_He_TTokep",
        L"KoTuK_B_KoCMoCe",
        L"Бублик",
        L"Gamer",
        L"Carolina",
        L"maksim",
        L"xoJloDHblu_paccyDok",
        L"Bluesmith",
        L"Убийца пьяных бабочек",
        L"Aria",
        L"kJlu4ka_kyBaJlDbI4",
        L"VaMp1R",
        L"Абу хазми буль-буль Пятар",
        L"Vacuum",
        L"fishka",
        L"BaJIepa-TIOMEHb72rus*",
        L"CaJIo_B_IIIoKoJIaDe",
        L"n1mySelf.nO.Skill?",
        L"kraZy",
        L"Groll",
        L"^_^::п0каж1 CиCечкi::^_^",
        L"--==NURbI4==--",
        L"kpyTa9l_6a3yka",
        L"стремнаЯ",
        L"Bloodblade",
        L"Artyom",
        L"Kajikazahn",
        L"Интернет Бродилкин",
        L"Pesius",
        L"kpyTou_raHrcTep",
        L"Dianann",
        L"Hellgrove",
        L"4yDeca_Вa_u_ToJlbko",
        L"Nalmehelm",
        L"I am Batmen",
        L"sportsmen",
        L"Злыдень с карданом",
        L"Окуеть дайте две",
        L"Турбовозбудитель",
        L"Mr.Epic",
        L"onlyWH",
        L"_FANDER_",
        L"Lnker_Z",
        L"ZadNizza",
        L"totitot",
        L"kr@snuym@Kas1n",
        L"YNNAM",
        L"Na`Vimarkeloff~~~",
        L"CnuHorpbI3",
        L"Gamerok*",
        L"Artcross",
        L"ЕНот_riоТаскyH",
        L"BeautifulButterFly",
        L"Limonix",
        L"O4eHb_3acTeHb4uBa",
        L"SemenStrapon",
        L"Youdontknowwhoiam",
        L"Интим не предлагать",
        L"Drelann",
        L"Saigrinn",
        L"Imperator",
        L"Ka6aHTpocTHukoBbIu",
        L"Robby",
        L"EBASH@",
        L"Mightsong",
        L"HacTblpHblu_MaJlb4uk",
        L"Shalidar",
        L"Destroy_ST",
        L"DJON NIK",
        L"Mogore",
        L"FranzyFox",
        L"Brett",
        L"ALFAdogs*MoTb1JLek.",
        L"Ferdinand",
        L"Mr.BĬØǾĐ",
        L"Sliper",
        L"siemens",
        L"BupTyo3Ha9l_BoDuJIa",
        L"PrikoliSt",
        L"SkIL AnGGeLL",
        L"Сплюнахнетрогать",
        L"|YrKa|",
        L"|ElusivE|tM|***MANIAC***",
        L"den24rus",
        L"Like pa$an",
        L"PROST_FROST",
        L"bonaqua.broforaquaminerale",
        L"ApXuTekToR",
        L"ugrozer",
        L"alkaida!!!",
        L"Dopingjanjak",
        L"3akoH4eHHblu_6a6Huk",
        L"TpyCbI_CMepTu_34",
        L"Goldsong",
        L"Mrs.Viktoria",
        L"3aHo3a_B_TpyCaX",
        L"Cardinalli",
        L"Xo6oT",
        L"Тр@вокYр",
        L"unstoppable",
        L"Дедуськина бабуська",
        L"~hekeem4'V12",
        L"cepDuTblu_oxoTHuk",
        L"Goldendefender",
        L"Mr_Jeйson_",
        L"CripsBoy",
        L"Apotheoses of Latzaf",
        L"панда",
        L"TaeKwonDo",
        L"[X]odok 3anuB0M",
        L"Kristalos",
        L"Вечный ньюб!",
        L"DarkAngelKael",
        L"IcePower",
        L"Estell",
        L"SAHARWHORES",
        L"James",
        L"edmond",
        L"Daisida",
        L"Я вернулась из блока",
        L"Боги-Войны",
        L"MaWKa_BepHu_Mou_TpyCbl",
        L"6oJlbLLlou_BeceJlb4ak",
        L"Papa_v_tanke_86",
        L"~TheEnD~",
        L"Esteban",
        L"kaptic",
        L"уборщик подвижного состава",
        L"KenTos",
        L"Блоха в скафандре",
        L"gameqq",
        L"Anadi",
        L"AkuToR",
        L"PokemonGo",
        L"VIPsona445",
        L"C0HHblU_X0Pb0K",
        L"CTyDeHTka_B_Me4Tax",
        L"Aleksei",
        L"Feloghma",
        L"TTpocTo_AHreJl",
        L"CTpouHa9l_MuJlaLLlka",
        L"PeaJlbHo_ka3aHoBa",
        L"Manarn",
        L"Kibei",
        L"aDeKBaT~u3~aDa;3",
        L"Vikus",
        L"Торговец плотью",
        L"Cezius",
        L"LEX.TV",
        L"Loni",
        L"MaGnUm",
        L"EazyPizzy",
        L"Blood warrior",
        L"Adokelv",
        L"ENQEE",
        L"RAMPAGE",
        L"fanNat1c",
        L"AloneInTheDark",
        L"OCA_B_TPYCAX",
        L"_ХиТросТь_",
        L"YOUTOUCHMYTRALALA",
        L"Ivory",
        L"Ca/IaT_O/IuBbE",
        L"Девственник всея Руси",
        L"ВѼчко",
        L"Агрессивное дно",
        L"Kulanara",
        L"~IOc9I~",
        L"Moril",
        L"MarilynMonroe",
        L"bass",
        L"Bedy",
        L"Gusar",
        L"волчонок",
        L"]Mr.Сексуальность[",
        L"Одиночество в сети",
        L"Petus",
        L"ATOMY",
        L"whitewings",
        L"Essner",
        L"Celestina",
        L"LLle9l_u_cpa3y_Horu",
        L"POBEDITEL_PO_ZHIZNI",
        L"awh705",
        L"MegaCRAFT",
        L"Anaya",
        L"DeaD_MaKcNm",
        L"Grewnik",
        L"kpyTa",
        L"SorryIamtopik",
        L"V I M E R",
        L"Фрося_Бурлакова",
        L"Albrough",
        L"Chessman",
        L"Ledy Frozen",
        L"TIepecTaHbTe_Bop4aTb",
        L"hello",
        L"KUMO",
        L"Mix_Fight_M-1>>>ArturPirozhkov",
        L"TheEndSkrillex",
        L"KiiNNG",
        L"KPACABA__6E3__TPYCOB",
        L"LuckyBoy",
        L"Y_U_R_I_K",
        L"Marian",
        L"Bele",
        L"Dawnterror",
        L"ARS_ONE",
        L"Evoluciya",
        L"Утка_в_тапках",
        L"Mr.Олимпик",
        L"HeTpe3Bblu_KoT",
        L"__Ner__",
        L"icebaer",
        L"DURASHKA",
        L"Sps_vbr_za_komandu",
        L"Mr.Zadrot-=SmILe=-",
        L"To4Ho_He_CTaTuCT",
        L"шнайдер",
        L"Кошерный Доктор",
        L"TeraMiraBili",
        L"4EJIOBEKCIIAPIA",
        L"Wry",
        L"B_koHTakTe_BcerDa",
        L"Kissofdeath",
        L"Какаши Жмуруками",
        L"пурген",
        L"REALKENT",
        L"усы-лапы-хвост",
        L".EVi|",
        L"Dulkree",
        L"Mr.Nazik",
        L"-bLaZiN-",
        L"Mr.Limbo",
        L"Pozitiw4ik",
        L"EasyHUIsy",
        L"Do hyia delov analnbI’ zud",
        L"ToJlcTblu_TTapTu3aH",
        L"ILUSHENKA",
        L"BACEG",
        L"kovalo",
        L"Virus",
        L"95Che|maGnum#",
        L"Ktylxy",
        L"PAKyI0_KaK_M0ry",
        L"KENDALLSB",
        L"ХАЛЯВА НА БАЗЕ",
        L"3aTTeKaHka_Co_CMeTaHkou",
        L"pushistiy_zahvatchik",
        L"Jimmy/A/",
        L"Blackkiller",
        L"light of life",
        L"DEAD-_-Е_Y_E",
        L"Схватка 2 якодзун",
        L"Dule",
        L"MuJla9l_TBo9l",
        L"•SukaBled•",
        L"BlacKDraGon|-=JIeXa=-",
        L"FairyTail>Brasida",
        L"Golkree",
        L"*Dinoza6eJIka*!?",
        L"[!_m0kal v b0kal_!]",
        L"ALISH",
        L"***MaDaGasCaR~H*O*M*9*K",
        L"F@x_13rus.",
        L"Saumitra::",
        L"100gramoВИЧ",
        L"RapTor",
        L"XapakTep_Tak_Ce6e",
        L"Bremar",
        L"Мыха-наруха",
        L"Agantrius",
        L"MatyxaCS",
        L"Kpy4y_poMaHbl",
        L"OcTaTT_6eHDep",
        L"Your perdAk is under AttAck",
        L"Пендальф - Виз",
        L"EnderDe",
        L"В ожидании чуда",
        L"~fanatik~",
        L"CMETAHKA33",
        L"Mi$$ P0ziTiFF",
        L"Beabor",
        L"De'Team*>>Nirvana",
        L"gamERROR*channelik",
        L"Cherry_Pie",
        L"jo***",
        L"MATPOC",
        L"☢ПøŽϋŦΰ฿पÛķ®☢",
        L"ProLaminGNightRuSHMa/|blLLl",
        L"666GESTAPO666",
        L"Страшный симпатюга",
        L"Anayamath",
        L"Guardian#",
        L"F.B.I.Fox_Malder",
        L"Марс атакует",
        L"He_Tporau_xoJloguJlbHuk",
        L"sXc>WooDoo",
        L"SpeedBeast",
        L"Гомик в Деревне",
        L"Valtierra",
        L"PoniX",
        L"Rockworm",
        L"хР_пСих",
        L"den34rus",
        L"€to ne to o 4em tbI podymal ㋛",
        L"Gavinrazan",
        L"Ballalore",
        L"NAPAS",
        L"RZNKyM",
        L"carskyy",
        L"IIuBacuk",
        L"Dr Karl",
        L"Mr.KoT",
        L"MetiS",
        L"Gangsta",
        L"Brasida",
        L"OtecVasiliy",
        L"BRADEAGA",
        L"Casimira",
        L"eM_KapToLLLKy_c_4ecHoKoM",
        L"Неиграю в УО",
        L"mousesportslBblKJllO4ATEJlb",
        L"DeDc4uTamu",
        L"TOJIK",
        L"vedro",
        L"[Х]o4y B kJIaH Ho 9 E6JIaH",
        L"ЖиЗнЕнНаЯ ДеВоЧкА",
        L"НОСОК_В_ТАНКЕ",
        L"BzZzZz",
        L"ropDblu_MaJlblu",
        L"KATEPuHA_3a6EPu_Tpycbl",
        L"MaZaHaKa",
        L"ANTMAN",
        L"Nejas",
        L"Ky6@Hb>NPS",
        L"CTapbII/I",
        L"Aga",
        L"FaRToBuU_",
        L"XPEH_BAM_PAKAM",
        L"Doule",
        L"Bags_Banny",
        L"CkpoMHa9l_3auHbka",
        L"Xo4y_o6paTHo_B_wkoJly",
        L"(B>K)MakcumJKE",
        L"Неопознанный Летающий Мужик",
        L"Global Silver Elit™",
        L"Pycckuu_ApxuTekTop",
        L"Slonski",
        L"velikolepnaya",
        L"Walker",
        L"LSD56RUS",
        L"снегурка_в_чулках",
        L"Pepsi-cola(nosound)*)",
        L"HacTeHbKa",
        L"Ya y mamki Dyra4oK ?",
        L"PoMiDoR4Ik",
        L"OFH|Pe4albka",
        L"limon",
        L"Dj MainCrafter",
        L"Balamut:)",
        L"krest#Justdoit",
        L"petrovich",
        L"mooch",
        L"Shadowmoon",
        L"Ама3онка",
        L"T1m/a/_________________________",
        L"Na`Vi_CosaNost",
        L"Muhammad~Ali=)",
        L"KyKyPy3a",
        L"Benny",
        L".оО Мышка-стрептизёрша Оо.",
        L"Derm",
        L"сексуальная козявка",
        L"The-BesTGreen",
        L"cegamegabaton",
        L"Fenrilar",
        L"Nector Play",
        L"XaCTJl6aCTJl(DurkO)",
        L"inzaghi",
        L"PacToMaH:)",
        L"CS__2017__",
        L"_ВкуСныЙ_КекС_ммМ_",
        L"люша",
        L"Skapura",
        L"Rostowski161rus)))",
        L"тараканище_без_зубастое",
        L"F4nt4st",
        L"EcJLu CEKCA B }|{u3Hu HET, CgEJLau CAM Ce6E MuHeT ?",
        L"Aurus",
        L"Pro_Killa.::Mix::.",
        L"Persey?!",
        L"Kiddo",
        L"KoBeJI.ua.MONSTER",
        L"Remer",
        L"Jasper",
        L"APTA_HE_TPOHb_TAHK",
        L"katalonec",
        L"Algrinus",
        L"MrRebrik",
        L"**IIIpyc[bI] HA rOLOBe**",
        L"urpbl_pa3yMa",
        L"Corin",
        L"TMManusflyrush",
        L"Whiteforge",
        L"Юрец всем в торец",
        L"spiker",
        L"королЕва задрот",
        L"Looney21Rus",
        L"cs16Pl000andrey",
        L"Anabor",
        L"Kristal_Girl",
        L"pahan",
        L"MoJlogou_DapTaHb9lH",
        L"pa3BJlekal-0cb_TyTa",
        L"Тарелочка Борщя",
        L"LeG1on_Vova_1324",
        L"Ŧђє≈þ®ø",
        L"Cy/7ePKoPoBka=>Trash",
        L"G.S.H.|.::VOLK::.",
        L"*aMcTepDaM*46rus",
        L"BkycHoe_TIe4eHbko",
        L"eBaIIIy_KaK_4ItER",
        L"Rolex-X",
        L"Ч. У. М. А.",
        L"MrSmiley",
        L"FFVINNI",
        L"cMokuMo",
        L"Kirillador",
        L"Доместос_супер_грязь",
        L"Мися",
        L"PACMAN",
        L"LYOSHA",
        L"Sharks|Otmorozok11",
        L"BALLER#",
        L"rushenkel",
        L"Ararn",
        L"Aleks",
        L"whatthefuck!?",
        L"lTC.fOrestl-=DeLUX=-",
        L"--=DevilJin=---",
        L"Majind",
        L"piy-piy",
        L"Пять_недель_на_возд­ушном_шаре",
        L"Holloway",
        L"Ne7ative;",
        L"Тэ",
        L"Beranyle",
        L"Hyper best",
        L"Anardin",
        L"Твой Mr.PropeR",
        L"DoKToR",
        L"25cm_6oJIu",
        L"RnDGLock_",
        L"LemoniSniket`",
        L"Chips",
        L"Ночью под мостом и с топором",
        L"Yassaui",
        L"bdex6ega",
        L"Jamaica.",
        L"Eric228GanjaTeam",
        L"RnDShalun|onlyuspstylE:p",
        L"Porno",
        L"Монитор Клавиатурович",
        L"KJlaccHblu_BeceJlb4ak",
        L"Dork",
        L"Super_Nitro",
        L"IgrokWicked",
        L"(((((KOT)))))",
        L"realOnline",
        L"Злой димедрол",
        L"Doubei",
        L"Sajkeee",
        L"Daniil",
        L"00:0003(Ylb9nobsk)",
        L"Earline",
        L"Sadi",
        L"PoezD_B_PisDu",
        L"OpenFier_Djoker",
        L"Snayper23",
        L"Beceluu'Clonuk",
        L"Alpha",
        L"PISTONSZAO",
        L"BaiKov",
        L"VADZ9_AKA_MORG_FTF!?",
        L"sp1rtQ",
        L"nazgul#/",
        L"ak-47thisismylive",
        L"Death in the eyes",
        L"kilir18",
        L"RangePower",
        L"assassin",
        L"Ровин",
        L"CTAPllEP",
        L"***HunteR***",
        L"Sann",
        L"Doomwind",
        L"MELKAT",
        L"Ghodwyn",
        L"M-SapFira",
        L"ГУСЁК",
        L"Hanter",
        L"Хубрик",
        L"CrazzzyChel",
        L"zilovec",
        L"HyTblBaLLLe",
        L"принцесса дури",
        L"Убиваю принцесс, спасаю драконов",
        L"Reebok",
        L"Mynameis",
        L"LinKolN",
        L"Tojagar",
        L"MuJIeHbkoe_pro",
        L"da?barada",
        L"KARIM",
        L"Anonym",
        L"Casper",
        L"Sosok-Admina",
        L"Auginn",
        L"Последнее слово чебурашки",
        L"Anarant",
        L"KOKOC_u3_KOCMOCA",
        L"Шишколобый_Гнидодав",
        L"SUPER BRO",
        L"✖ЛиЧнОсТь✖",
        L"Aguray",
        L"MuJlaLLlka_eTo_To4Ha",
        L"dead_user",
        L"Rinder",
        L"Fearlessrunner",
        L"Classik.",
        L"splatt.JE",
        L"Adrienrad",
        L"Mikakora",
        L"Groran",
        L"buharskiy",
        L"TTo4Tu_B_LLlokoJlage",
        L"Дед-отмороз",
        L":m0NesY",
        L"TTo_uMeHu_3Be3ga",
        L"Balducci",
        L"Jessia",
        L"TIpu9lTHoe_cHoBugeHue",
        L"empty",
        L"TTpuroToBuTb_aMJleTuk",
        L"DOMO",
        L"CHIZARIK",
        L"3a_PyJleM_LLlkoJloTa",
        L"ТРАВА_НЕ_НАРКОТИК",
        L"Live-Evil",
        L"смерть с косой",
        L"pykan",
        L"OkApple*",
        L"CrazyMegaAether™ ®",
        L"MReGoR",
        L"♛ĂʟӍάƷ♛ツ",
        L"Dobar",
        L"basoTa_faMiLy",
        L"Ra$PizDAY",
        L"Travis",
        L"Ishnlv",
        L"AcideAA",
        L"BepHyJlc9l_c_JlyHbl",
        L"Beazelv",
        L"ya,oslenokia!?",
        L"4epToBcku_kpyTa9l",
        L"marsellos",
        L"Drink.!!!",
        L"Шаман-наркоман",
        L"Taulmaran",
        L"XpycT9lLLlka_u3_TecTa",
        L"Gabella",
        L"DarkFire",
        L"DOLBITMilayaDevyIIIka",
        L"Fashist",
        L"007:Nastja",
        L"ℋ∑Ꭿ₮Ꮥℋტ₮",
        L"VPLOKO",
        L"Мозги в носке",
        L"Московская Колхозница",
        L"@lphA",
        L"Onan",
        L"Товарищ в гражданском",
        L"gaTbI4To!?",
        L"Zuluzahn",
        L"Вонючий Суслик переросток",
        L"BLATNOY",
        L"G.S.H.|ONLYVODKA",
        L"TyT_Te6e_He_3Decb",
        L"PROJECT",
        L"в клеточку",
        L"лучший из худших",
        L"Mamacka3aJlae6aw",
        L"p*zda tebe",
        L"KpyTa9l_XyJluraHka",
        L"Kharkov# RaKFoRd",
        L"Дачный душ Зеленовка",
        L"Mr.ByBlIk",
        L"Bonduelle",
        L"TToJly_TIokep",
        L"загорелая роза",
        L"www.ccgAme.cn",
        L"GameGuru",
        L"O4apoBaHHa9l",
        L"CAHEK73",
        L"Ж.У.Р.И.К",
        L"Keragas",
        L"Armin",
        L"Дырка в голове",
        L"Mr.spice",
        L"13ekeM`13ee`jO",
        L"NightRidersYT",
        L"Black_Star",
        L"Mirrox",
        L"GoJIoVa DoMa 谷",
        L"Ermak",
        L"0CEMEH1TEJIb 6a6yJIek ?",
        L"B_MapTuHu_yToHyJla",
        L"Linkovich",
        L"OTBeTcTBeHHblu_4yBak",
        L"mr.freedom!",
        L"Лохматая Волчица",
        L"Alogos",
        L"JlackoBblu_aHreJlok",
        L"Yahoo!G0",
        L"Bogka",
        L"PLOXOY.LEFOU!",
        L"XoXolDeRzKySyka13UA",
        L"Hu_CTblDA_Hu_COBECTu",
        L"Nervok",
        L"Bragrinn",
        L"DarkAngel",
        L"урок с паяльником",
        L"Neopren_aka_brn",
        L"Lorena",
        L"Hucama",
        L"Sam",
        L"/7eXaPb TBOEu MAMKu",
        L"Стёпикмен`",
        L"BeatiFuLLKiLLeR",
        L"Daile",
        L"ОченьПриятно-Царь",
        L"Garfield",
        L"TTyTeBka_B_Mup",
        L"He_3eMHou_kpacoTbl",
        L"GAWWA",
        L"Broadcaster",
        L"Fol",
        L"begemot",
        L"oceHb_3oJloTa9l",
        L"Bluelytning",
        L"O.N.Y.X",
        L"Cordadi",
        L"Palladium",
        L"Kalar",
        L"HOCOK_MAMOHTA",
        L"обиженная дождем",
        L"JlenecTok_JloToca",
        L"кураГАЛЯ",
        L"S.T.A.L.K.E.R",
        L"a.k***CJIe/7oY***",
        L"Потолковый Лампонюх",
        L"Chillkiller",
        L"D®eam",
        L"3/I0u_0/IeHb",
        L"eAx-Tera~>",
        L"Doventor",
        L"CTAPyXu_CMOTPuAT",
        L"Полулысое недоразумение",
        L"BatyrkhanKazaX",
        L"Miss_insta",
        L"Andrew Juice",
        L"SKOMOPOHKAS",
        L"MbIWb_B_TPYCAX",
        L"гнойная палочка",
        L"Xyk_cnpaBa_28RUS",
        L"HepBbI_B_HopMe",
        L"Apolik",
        L"NoSwear",
        L"uknown",
        L"Scorpion777",
        L"Cicale",
        L"-=B!ZON=-",
        L"СчАсТлИвЫй ХоРек",
        L"Nickolas",
        L"Дискон",
        L"3eJleHa9l_TpaBka",
        L"DonCorleone(VitoAndolini)",
        L"Рыбка с запошком",
        L"..::Zero::..",
        L"~ooorgazmoo~",
        L"FuckYeah:D",
        L"Обожённый_лунным_св­етоМ",
        L"Mugal",
        L"Lucky Sunshine",
        L"NicGamers",
        L"Kison",
        L"Neophyte Believer",
        L"PingueBlueSky",
        L"3akpblTa_oT_Bcex",
        L"PaRoVozik_KotOriY_CmoG",
        L"topleHoemolo4ko:D",
        L"Злой Гусь",
        L"волшебная клизма",
        L"Face of death",
        L"?Кошак",
        L"Seksualnayapanda",
        L"blac wolf",
        L"Mysik_B_Tpycax",
        L"RnDAndryxa|onlyuspstylE:p",
        L"NAGORA",
        L"Miss_Yasia",
        L"didok!",
        L"Dailmaran",
        L"ToJlbko_DJl9l_Te69l",
        L"белка-хотелка",
        L"freZzzzz?!",
        L"Wtf//BsV~1st|>?",
        L"ВОРЮГА-АНАНЮГА",
        L"Кот шашлык",
        L"Fokelv",
        L"Lavonda",
        L"Asyasya",
        L"Высоковольтный Майонез",
        L"Emswiler",
        L"BIGBRO",
        L"StackerMan",
        L"HellRey",
        L"antinoob",
        L"Romka_",
        L"Убийца матрёшек",
        L"CaMa_ucTuHa",
        L"Quemal",
        L"FARTOVII73RUSS!!!",
        L"TaTar1n|Cyx",
        L"Landameena",
        L"moawrd",
        L"Adoradwyn",
        L"-=Lstrel=-",
        L"УбЬю ТаПкОм",
        L"ǷȫѮѦ",
        L"CaHuTaP Tya/eToB",
        L"Ga",
        L"Mechta*116rus",
        L"CrustaL",
        L"Yozshusida",
        L"Полнолуние",
        L"razbe6awer.c/",
        L"Korol_sliva",
        L"Kajin",
        L"`Jke#1",
        L"KoJlo6ok_B_TpyCaX",
        L"Sambist",
        L"Froststalker",
        L"BeCeJIyH4uK",
        L"Nilador",
        L"KRASNODAR",
        L"-=BalacaTbiu=-",
        L"npocToJIePkA",
        L"Colton",
        L"IPServera77.220.182.77:27015",
        L"paHgomHoe_gHuwe",
        L"Dular",
        L"Rustin",
        L"Сильвестр в столовой",
        L"PyKA_B_TPyCAX",
        L"not|eNvy.",
        L"Divais>KiPeS`h",
        L"Mad Irishman",
        L"WalkMan",
        L"caM6yka_B_TTo4eTe",
        L"chopper",
        L"Mannes",
        L"TheChemodan",
        L"Jameson",
        L"ПлАсТеЛиН ОвЕц",
        L"m.@.s.t.e.r",
        L"ЗелеБоба",
        L"TERAN",
        L"Bladebringer",
        L"General_Zadov",
        L"Morluzius",
        L"ptichka",
        L"Boo Boo",
        L"Monster",
        L"LsB|TakTuk",
        L"Dused",
        L"Predator",
        L"homyak",
        L"Злобный_бульбулятор",
        L"Diananrad",
        L"смерть админа",
        L"ЗОМби_КРОШИТ_П@Ц@нов",
        L"pALkA",
        L"MacTep_Yoba",
        L"Сочная ставка",
        L"Plaster",
        L"сволочь в перчатках",
        L"Cereswyn",
        L"Buzz",
        L"CJlaDkoe_xo4y",
        L"Dumuro",
        L"Carrol",
        L"c4acTb9l_Kyco4ek",
        L"ALMIK",
        L"Дибил - Пет докеби",
        L"Sairus",
        L"Hu4ero_He_3Hal-O",
        L"Bro-AmA-pro",
        L"Brave Indigo Lobster",
        L"Dracula_Snow",
        L"Mr.Benqs",
        L"КОНЬ_як",
        L"DenDy",
        L"jakonta",
        L"krisa",
        L"Veillon",
        L"ejuk:D",
        L"Хренабубка",
        L"DeMpDeeZ",
        L"Balladordana",
        L"Любовница Смерти",
        L"pr!zrak?!",
        L"AMG///",
        L"Ba3Typ6o",
        L"Kenny",
        L"XJiOn_u_PAKA_HET",
        L"iceFice",
        L"KuTauckuu_DpakoH4uk",
        L"black coffe",
        L"Dyx_Heno6eDuM",
        L"Muriel",
        L"Bogra",
        L"JlaTTyLLlka",
        L"Неуравновешанный хомяк убийца",
        L"Amhirishes",
        L"БОМЖ",
        L"I_LoVe_KiLL_To_You",
        L"HLTV3aPycb",
        L"Beazezel",
        L"Ba3eJIuHoBa9I_OIOe9I",
        L"САМ ТАКОЙ",
        L"kill_proaim",
        L"Cama9go6pa9geBo4ka*",
        L"Краснопьяточный грядкоторчатель",
        L"Kirilhala",
        L"TpaxagpoM",
        L"Shortino",
        L"ПрИвЕт_В_ПрИцЕлЕ_AwP",
        L"nocomments",
        L"Buzaghma",
        L"Stinky",
        L"BceM_Do6pa_xo4y",
        L"Frlas",
        L"Brocker",
        L"Кура-с ИнтелеКтоМ",
        L"mamka_razrewila",
        L"Фиолетовый Пук",
        L"jukkacanada",
        L"MANGO54rus",
        L"Lala",
        L"Laureen",
        L"Lehtomaki",
        L"злобный бурбулятор",
        L"Mozragore",
        L"Obzorshik ot boga",
        L"Buriwield",
        L"Mpa4Hblu_reHepaJl",
        L"BuPyC",
        L"Blackfire",
        L"Beechum",
        L"касатик-М-16",
        L"⎞★f@ntA★⎛",
        L"Aurinrad",
        L"RSMyJIbTpa)",
        L"MaLLIka_o4apoBaLLlka",
        L"Deloge",
        L"Manesenci",
        L"DoseR",
        L"Don_Vortex",
        L"Alesia",
        L"Datrim",
        L"Force>>",
        L"koresh",
        L"GrizeR",
        L"OJluMTIuuckuu_Pe3epB",
        L"Cegrinn",
        L"B_I7JIeH_He_6PaTb",
        L"Andronrad",
        L"-Sket-M@n-",
        L"ASHABIST",
        L"HAgu6ATOP_B_TPyCAX",
        L"Ate1st",
        L"PaK_0TIIIeJIbHuK",
        L"-=Deal=-",
        L"JOPAAA!",
        L"Ларра",
        L"Broadraven",
        L"red_Army_161rus",
        L"Осторожно Танк",
        L"ⒶaŴÞ ︻デ═一 -™",
        L"CoolBoy",
        L"MONCTEP",
        L"Arashirn",
        L"kanibal",
        L"C_BepTyXu_B_PaKa",
        L"Feliks",
        L"SkuZoppO",
        L"Mac",
        L"PASkaL'-",
        L"nesteaforNastia",
        L"Tor4y.bec",
        L"ALEXandr_is_Rassia",
        L"BECe^JIbIu^ KOHb",
        L"L.V.TDed-Xacana",
        L"Fan-good",
        L"SvYt@yA_]{aRtOsHkA",
        L"ANUARIK",
        L"†ǾЂŁìvîŌ₦†",
        L"Anargas",
        L"Ангел-Предохранитель",
        L"Хотящий",
        L"HeHacto9wuu’ Mapkeloff",
        L"s.w.a.t.007",
        L"HacTeHa*",
        L"ODAS",
        L"S.W.A.T",
        L"Aurinara",
        L"Balladolbine",
        L"Тролль из уборной",
        L"Нечто",
        L"DAMAGE",
        L"JayZee",
        L"KKKArtemka14FCV88",
        L"AW_B_A_N_D_I_T",
        L"Блoха в Сарафане",
        L"LP~/A.M.P",
        L"Vito_Scaletta",
        L"shustry_cherepax",
        L"Mutius",
        L"NerouN",
        L"manga",
        L"Pirozhok_s_kartoshkoi",
        L"roRdeeBkaNiNo",
        L"Brakree",
        L"B-E-T-E-P-A-H",
        L"TTpekpacHoe_DaJleko",
        L"AgREsor",
        L"Cnacu6o_Dedy_3a_CaHku",
        L"Arashigis",
        L"nonamers|_/|amo",
        L"TTeJlbmeHu_ypaJlbckue",
        L"Josephina",
        L"Медуза в Танке",
        L"Dunken",
        L"YT| DeByшka",
        L"DISCOVER",
        L"tuki-tuki",
        L"~/7poka3Hik~",
        L"Ghile",
        L"CMEPT",
        L"Ranny",
        L">_VaD0sInA_",
        L"KyKyPy3uHa",
        L"kypuTb_He_kpyTo",
        L"Flari",
        L"Happy",
        L"MR_Xaker",
        L"Mazushicage",
        L"saneklee",
        L"BlackLife",
        L"Silverweaver",
        L"Dухман",
        L"+1GENERAL****",
        L"Aralar",
        L"Zuluktilar",
        L"old_demon",
        L"Shymkent",
        L"The_Game",
        L"ПРОЗРАЧНАЯ_РУБАШКА(­ОНА)",
        L"Smoky_noob",
        L"Von_Marus",
        L"DenneM",
        L"Cyxue_Tpycuku",
        L"♥˜”*°•П☈☉сTи ̴Ʒа βсЁ•°*”˜ ♥",
        L"Anayarin",
        L"DOMINIK",
        L"На_Опыте",
        L"Клон из пробирки №13",
        L"tuz13",
        L"IDon'tCare",
        L"oTpa3uJlacb_B_o3epe",
        L"Goldcliff",
        L"рыло_кирпичем",
        L"Лекарь-Костоправ",
        L"|uBoU`",
        L"MYDAK",
        L"Creatures!",
        L"DeadStrong",
        L"LLapb-->MuxauJI",
        L"sladkoegka",
        L"edrillo",
        L"ŠẂẪĢ™»/ŁẴÐ",
        L"FEISKO",
        L"Kuku",
        L"ALLIGATOR",
        L"Toni Mantana",
        L"ForeVeR_In_yoUr_drEaMs",
        L"Ananaya",
        L"?by Pan[I]ca#.Skill...",
        L"Nuadarius",
        L"KAKASHKA",
        L"TIpocTo_He_xaMu",
        L"Какуля",
        L"lopata",
        L"Holdik",
        L"S!nGL",
        L"Biggie",
        L"TRATIL---------------->",
        L"CaMo_c4acTbe",
        L"Alsasida",
        L"Тюленьвсяжопавракуш­ках",
        L"PROSTOkAsPeR(",
        L"Voron",
        L"IceStorm",
        L"M@TRIX",
        L"RHykoBu4",
        L"Кина не будет",
        L"He_/7peT",
        L"Garon",
        L"Poudrier",
        L".alex'",
        L"Gavryuwa",
        L"Чухонский культиватор",
        L"evile-maeee",
        L"*(_So_SmisloM_)*",
        L"JIapucy_uBaHoBHy_x04y",
        L"JoJoshakar",
        L"Helpless Sapphire",
        L"eTo_akkayHT_6occa",
        L"81)*GamEOveR*",
        L"Mucc_o4apoBaLLlka",
        L"Arith",
        L"добрый жук",
        L"Akinozuru",
        L"alexxx",
        L"Wormax_Book",
        L"Kizuru",
        L"Sexy_ПуПоК",
        L"веснушка",
        L"отдамся за 5 рублей",
        L"KoTJleTa_JloBaHDoca",
        L"lucky-werse",
        L"MDK|Vnb.SnorkI",
        L"TIpukoJlucTka",
        L"lambada102rus",
        L"NeoNew",
        L"Don1**",
        L"НЕ_ТАБАК!",
        L"Летучий Олень",
        L"Стон водопада",
        L"Mack",
        L"dodikxyev",
        L"Faurn",
        L"aimboter",
        L"Botskill:(",
        L"Doomsong",
        L"Barg",
        L"CAJIO_C_4ECHOKOM",
        L"Злой зелёный таракан",
        L"TpaBa_MypoBa",
        L"{X}o4y kak PR0™ moGy kak DNO",
        L"Jytr@n`_0!",
        L"TIpaBo_roJloca",
        L"Earl",
        L"Zenaida",
        L"Galore",
        L"abortnay_belka",
        L"Crocus",
        L"Nabar",
        L"Shadowrunner",
        L"Nopreviousconnection",
        L"TTo3uTuBHoe_MblLLlJleHue",
        L"Thunderblade",
        L"NickMHE3anuJIuJI!6bICTPO619",
        L"me.wizzy",
        L"RaZnos_/74eJIa*(.)(.):D",
        L"( .) ( .)",
        L"TaTapcTaH***CyTaH",
        L"4ebyrek",
        L"Dalarin",
        L"٩(×̯×)۶ InoPLANetSInin ٩(×̯×)۶",
        L"Necroa",
        L"mis'eFonBaron",
        L"AFTERLIFE",
        L"AlaEva",
        L"Мы Взрывали Апельсин",
        L"Крытый медным тазом",
        L"poxyimolodoi",
        L"LowSkill",
        L"СМЕТАНКА_ДЛЯ_КОТОВ",
        L"Nastena",
        L"Dissolutem1k`",
        L"Cocucka_u3_KocMoca",
        L"TAMBOVS WOLF",
        L"maxvel008",
        L"СoC ok",
        L"Ma)l(or",
        L"6a6ka Иa {Х}odylЯx",
        L"Pala4ka+18",
        L"|SPAS|MaXiMu(-_-)",
        L"greenPEACE=*",
        L"M@DM@X",
        L"NO_unnamed:)",
        L"(c)mPaHa'Oz",
        L"МАЛЬЧИК_НА_САНКАХ",
        L"boDRyi",
        L"vooltex",
        L"*GRAF",
        L"ARE",
        L"TIJlaTuHoBblu_ypoBeHb",
        L"Капитан Джек Поскорей",
        L"Iguana",
        L"Jeka_B_WKOJIE_6e3_TrycoB",
        L"Orsburn",
        L"Umthis",
        L"Android",
        L"Knucklesxd777",
        L"Не убивай лошадь",
        L"iiiiiiiizzzzzoooott",
        L"F.C.S.M",
        L"CJIOHuK_B_HoPKe",
        L"zmhmmm",
        L"Gartuz",
        L"Leo/EbA*RZN*",
        L"Rampage_style",
        L"nellon",
        L"Heino",
        L"ﻩ*ﻩ*ﻩСнЕжИнКа_Из_КаПлИ_дОжДяﻩ*ﻩ*ﻩ",
        L"Йа КреведКО",
        L"weltkind",
        L"Boraston",
        L"Sharell",
        L"Я_ЕсТь_СтрЕлоК_От_БоГа:D",
        L"TyTa_He_xaMuTb",
        L"Гамадрила",
        L"Грязный Боб",
        L"БаБа_В_КеДАхХх",
        L"CHoBa_3aMyTuM",
        L"Ak47)))",
        L"Боцман",
        L"Вылысыпыдыстка",
        L"Али Ибн Абдул Обстул Задом Бей",
        L"Бомж с рублёвки или Рублёвский Бомж",
        L"6ote*",
        L"zhenya)@",
        L"Mazie",
        L"GIMBAR_MASTER",
        L"KZ_JeeP_KZ",
        L"Tekasa",
        L"Akira",
        L"Blazer",
        L"dazz",
        L"МаДаМ [Бруньки]",
        L"3aBuDyuTe_MoJl4a",
        L"Digger",
        L"PROPIFPAF",
        L"qwerty",
        L"RoditeliyexaliBROpriexali",
        L">",
        L"Cesar",
        L"MyJIbTuK",
        L"bigben",
        L"mantur",
        L"}|{o/7a_4eIIIeTc9",
        L"miledi",
        L"Shisha",
        L"50_ottenkov_raka",
        L"Хомяк с пастой бленд а мед",
        L"B_TPycax_u_B_KEdax",
        L"Bugar",
        L"Je$$",
        L"TBo9l_HaBcerDa",
        L"HumaN~~~AngeL",
        L"Delirious",
        L"SmeHu_Huk__17",
        L"Dep3kuu_CaMypau",
        L"Flamebearer",
        L"MisheviuPlyshka))",
        L"Amoc*88",
        L"Agamaris",
        L"OskarDeLaHoya",
        L"Bagle",
        L"6aPPPakyDA",
        L"Р1ау_Ски11",
        L"Killer_pro",
        L"ilyhok1",
        L"Инквизитор",
        L"AJIeKc",
        L"N1_te_do",
        L"***_Te4a_NaPiKa_***",
        L"Truthstone",
        L"LuckyCat",
        L"CeperaCo4uncuxn1",
        L"без трусиков",
        L"Я вернулся из блока",
        L"ВОРУЮ_МАМОК",
        L"1noqda",
        L"luntik",
        L"Anayariel",
        L"MrPrizzrak",
        L"Tuktilar",
        L"Fenrilabar",
        L"ЛЮБАпытнаЯ.",
        L"GamerSilentSoldiers",
        L"Huggy Bear",
        L"Tell",
        L"AHTblTP",
        L"Kerarius",
        L"Твое имя۝⊂Һαחח℮Ŀ",
        L"Эксклюзивчик",
        L"Jarrett",
        L"TAHKETKA_KOTOBO3KA",
        L"kypuTe_6aM6yk",
        L"Слеш",
        L"GotFace~",
        L"Fordrelace",
        L"PsYcHo-PuNk",
        L"Вежливый снайпер",
        L"Плюхай Яйцедубович",
        L"DaIIIyJi9i_)**",
        L"Aurilas",
        L"рыцарь круглова стала",
        L"Adriege",
        L"̶T̶H̶E ̶E̶N̶D",
        L"Fenridal",
        L"G_fest*VlaDiMiroVna",
        L"olen'",
        L"Яростный кулак Джека",
        L"NuncyGanjaTeam",
        L"GoDFaTHeRBpatuwb::D",
        L"Megrel",
        L"nipper",
        L"FOXkRYSTAL07",
        L"famas`",
        L"BOND007",
        L"Tolik",
        L"**RoBiNgUd**",
        L"ALKACH",
        L"EgoDragonisMSK",
        L"alKoGoliK",
        L"QIWIVisaValera",
        L"YJIuTKA_B_TAHKE",
        L"AfinaS",
        L"Nice-ShoT-Hed-Show",
        L"Дед_Пыхто",
        L"КОВАРНОЕ ЛАМО",
        L"tERROR",
        L"FunnyPark",
        L"Nilawyn",
        L"MrJake",
        L"vipok:)",
        L"Eric",
        L"|’|uCe4Ka",
        L"BraZzers",
        L"6eJloeo6Jlako",
        L"Сиреневый_Турбовыбулькиватель",
        L"9lpka9l_DeByLLlka",
        L"Твоu’ МоX",
        L"()",
        L"kristiano",
        L"Дурочка-с-переулочк­а",
        L"Christoper",
        L"ExC!uT*",
        L"Samapuk",
        L"[ДЕМОН]",
        L"Crazy Men",
        L"Тухлый Чучо",
        L"vitalik",
        L"Cyrus",
        L"Паганый_нини",
        L"ocTpa9l_xpeHoBuHa",
        L"DeNoZaVR",
        L"trisemerki",
        L"XegIIIoTTaIIkOMBHoc",
        L"matrix",
        L"Лапочка",
        L"OLOLO-OLOLO-Ya-BoditeLb-NLO",
        L"БАБАЙКА",
        L"ss.tm",
        L"Канализационный Крыс",
        L"Блоха в униформе",
        L"///AMG*R19*",
        L"Drelandis",
        L"Tygot",
        L"Cs-Fannat|DRAMM_MAlllINA",
        L"Nemo",
        L"Barius",
        L"Шум и Ярость",
        L"Lara",
        L"TvoSI Mamka",
        L"rpycTHblu_HblTuk",
        L"ELVIS",
        L"Пластун",
        L"-=SHARAP=-",
        L"ININIINFD",
        L"(+_+)",
        L"AleksandrK.",
        L"Kamuro",
        L"Adorardana",
        L"Amis",
        L"IceOne",
        L"Ane4ka",
        L"Zorro",
        L"BurnBitch",
        L"Анонимный_Дротер",
        L"DeTka_TToB3pocJleJla",
        L"Erkebulan",
        L"OneQ/L0veK",
        L"хранитель червя",
        L"☠_ПИСЕВТbIКАТЕJI`_☠",
        L"DR.KOKS",
        L"Mr.Freeman",
        L"шанс_года",
        L"Alex911ss",
        L"wt0lBLRlMur1k",
        L"Bonnie",
        L"NormalnoDa?",
        L"Alsathis",
        L"Sk@ZI",
        L"Sossiska",
        L"Major_Pain",
        L"ZombiRaher",
        L"Lairius",
        L"Fordretus",
        L"go6pblu'k0TkAREL",
        L"Yggnrad",
        L"4amcu9T",
        L"ImKIlkAAAAebta*",
        L"Felhathis",
        L"Посмотри Направо",
        L"Пихал Михалыч",
        L"DONwerewolf",
        L"Жуткость Тормозная",
        L"BÃBÝ",
        L"simba",
        L"tango",
        L"Dairn",
        L"DeTka_eTo_Poccu9l",
        L"MrBread",
        L"SexXim.23",
        L"Big_Jon",
        L"CheGuevara/ru",
        L"ШаУрМа МяУкАеТ",
        L"Хьуна ма хаза аватор карина...",
        L"Eddie",
        L"KJloyH_B_keDax",
        L"CTTJloLLlHou_TTo3uTuB4uk",
        L"ПУТИН",
        L"Мстящий за Зайца",
        L"Hinik",
        L"сам_себе_дед",
        L"TPyCbI_B_noJIoCKy",
        L"NSiS|Santa",
        L"BabyIIIkaTerminatr:)",
        L")(@OS**",
        L"Mini Star",
        L".:A.V.A.T.A.R.:.",
        L"kibas",
        L"MaJIbIw",
        L"Garad",
        L"LopD",
        L"HauBHa9l_Dupo4ka",
        L".:Em:.*=*medvidek*",
        L"npe3ugeHT_6eJIo4ek",
        L"˜”*°•.♥β поискﻉ дNа печали♥.•°*”˜.",
        L"Fresh~~~SICK",
        L"~>>AngelsOFDeatH",
        L"beetle",
        L"E.R.A",
        L"*О*Д*У*В*А*Н*Ч*И*К*­",
        L"ctapyxa",
        L"Dianardin",
        L"Bloody Revenge",
        L"st1kjkeee_34RUS",
        L"Felozan",
        L"JustGhostY",
        L"Lamphead",
        L"---MoJLoDoY---",
        L"Аквилон",
        L"hotelkin",
        L"Malolace",
        L"Borzy",
        L"Гордый птичка",
        L"SceNoxsunduk",
        L"Bandi",
        L"SpikeOne",
        L"KurWa*",
        L"BrainTor",
        L"Aridar",
        L"Fordrenius",
        L"Dorinis",
        L"Taazik",
        L"Mezuru",
        L"протри монитор",
        L"Lol_for_all",
        L"Ma3axXicT",
        L"Чо-по кличке волОс",
        L"Шиза -не приходит одна",
        L"Нифиги ни фея - мой ник))",
        L"KeFuP_LOLOKA",
        L"Inkant",
        L"sexy 6aTaH",
        L"Кривые Руки",
        L"Faedal",
        L"cs.Ka3aHb_pro.Game//ueL",
        L"AnnyMars",
        L"yMoTaHbIu`M@rio",
        L"Manb94ka",
        L"JEMBO_IVANOVO_37rus",
        L"Muwyn",
        L"KOKOS",
        L"KreKys Games",
        L"HellDragon",
        L"HoBoe_4To_To",
        L"oSka43",
        L"(TR)***SaDiK45***(TR)",
        L"BeeDeePee",
        L"Adorardred",
        L"Dagar",
        L"Kyty3off!?",
        L"Приведение в кроссовках",
        L"Ieltblu",
        L"MyZHik B JIo$iNAX",
        L"Y0ur_Bunny_Wr0te",
        L"DePeBo",
        L"kpendejib_c_caxapom",
        L"Kulahuginn",
        L"Rakot",
        L"_А жИзНь ЧуМаАа_",
        L"Ща воткну этот меч в твой глаз",
        L"Dek.spb.",
        L"Kless",
        L"Und3rgr0undxX__PyC/|@H4ik__Xx",
        L"Dogda",
        L"BepHuTe CaMoKaT ?",
        L"M9Ico_KyKyLL|ku",
        L"DuKe",
        L"Rendu",
        L"Dori",
        L"Aurich",
        L"Дермонтиновый убийца",
        L"Agalas",
        L"i_Pro",
        L"Lra_viva",
        L"DeadAsted",
        L"Matthew",
        L"Xo4y_6a6y",
        L"Taka9l_3a6aBHa9l",
        L"-=H@PKOM@H=-",
        L"KaPrAL",
        L"gentelman",
        L"KuLLlKuHaPyly",
        L"Конопляных Дел Мастер",
        L"TaPaKaH",
        L"Trueshaper",
        L"Coca|Cola",
        L"Thrasher",
        L"В_KyCTAX_OCTAHyCb_HABEPH",
        L"cop_zombie",
        L"Blackseeker",
        L"Anayadora",
        L"Felowield",
        L"|vaha|",
        L"Bukus",
        L"Zacki",
        L"CbIpOCTb_oT_HoCkA",
        L"S| ybil эtor0 4yВаkа",
        L"Evil_Shooterka",
        L"Mozgi_V_Noske",
        L"777-Vov4uk***43RUS***",
        L"KoJll-O4a9l_3aHo3a",
        L"Alsantrius",
        L"ideika",
        L"Passu za Adminky",
        L"kinovinoidevochkidvadcati",
        L"David",
        L"Static_X",
        L"hyli?",
        L"BuSiNkA",
        L"ҳ̸Ҳ̸ҳ ИλьЯ ҳ̸Ҳ̸ҳ",
        L"joker",
        L"TTo3uTuBHblu_4yBa4ek",
        L"kpacoTka_He_3eMHa9l",
        L"Kentpro*A_D_I_N*37rus*",
        L"Hutius",
        L"Bandilhala",
        L"Любовница_Смерти",
        L"3aHocuT_uHorВa",
        L"Kandis",
        L"DobriyGrisha",
        L"Altai",
        L"Hell.Pig",
        L"He_HaDo_TpoJlJluTb",
        L"Mr.Zadrot",
        L"RampageOG",
        L"roBopuTb_He_DeJlaTb",
        L"DanikBogdancev",
        L"Bandeross",
        L"Goshan",
        L"adik4ernyitripoloski",
        L"FaInA_TV",
        L"TPYTEHb",
        L"V.R.UDima_Bomj",
        L"TheReader_____________________",
        L"Ka)i(yrkuNaxyu",
        L"NoSOk_V_NoZDre",
        L"R.a.z.b.o.y.H.u.k.-A*",
        L"ASEDY",
        L"rAndo0m4uk",
        L"DeluxE",
        L"crazy_8",
        L"camper_bl9_promazal",
        L"Akta",
        L"DblMOK",
        L"MaMoNt",
        L"Ковбой Хагис",
        L"TaRaZ-KuKa",
        L"шаловливая пиранья",
        L"COLON:D",
        L"ApTeMkA/A/kot",
        L"Pokaaaaaaa______",
        L"Vandygriff",
        L"Estane",
        L"Ahnenerbe|weR`d()()m'`",
        L"Персонаж заблокирован!",
        L"$SImPoTяЖк@$",
        L"хвост_мышки_майкрософт",
        L"-=(l0Cb=-",
        L"LLlokoJlagHa9l",
        L"Moramar",
        L"Voodoojar",
        L"Яблоко Исаака Ньютона",
        L"navalny",
        L"Lexus",
        L"-=.Creat1ve.-",
        L"Razpizdos(:-0)",
        L"Ariulace",
        L"ВААЩЕ ЧУМАВОЙ ДИНАЗАВР",
        L"alibi",
        L"4еrtovka_3",
        L"Ingardia",
        L"Грустный такой Лосяра",
        L"kos~>",
        L"ΠΘΔΖΣΜΚΛ",
        L"BblLLlu6aJlou_kJlu4yT",
        L"kak_yDaB4uk_cTTok",
        L"VALTRA",
        L"Bine",
        L"Zed",
        L"JIbI$bIu’ a/7te|{aRb",
        L"VamPirE",
        L"krot",
        L"МАЛЬЧИК_И_ДЕВОЧКА.Б­УДЕШЬ_3им?",
        L"((T))_((I))_((M))_((E))_((X))",
        L"ImAGAl",
        L"TTpaBblu_HoCoK",
        L"Osetin*",
        L"Nathanael",
        L"Па3итИФф",
        L"CENSORED77",
        L"Daladred",
        L"OrenRashtmlZLO",
        L"k0f3sT",
        L"6a6ywka",
        L"GOP-STOP",
        L"e6aka",
        L"Kathrizar",
        L"bLiNchiK",
        L"Lipson",
        L"JonCofy",
        L"MNCTEPXED",
        L"Kerry",
        L"5gorSK",
        L"Трепанатор из Одессы",
        L"Pe3kuu_TIapeHek",
        L"|FL||Pist0nchik|",
        L"Boudreaux",
        L"интимный прыщик",
        L"Lords from Eldor",
        L"Ashot",
        L"MISTIK31",
        L"Nita",
        L"Заяц Боевой Ушастый",
        L"niNja",
        L"LoL",
        L"Я ТуТ_Ты_ТрУп0_0",
        L"Fireinthehole!",
        L"Mr.)l(uBou`",
        L"Whisperweaver",
        L"==AHAPXOTYPUCT==",
        L"SK.Ob*eBOO:S3aBDB",
        L"Lino4ka",
        L"Light Soul",
        L"kiler",
        L"ZM(sas)doc",
        L"Starix",
        L"ГорячаяЛегенда",
        L"86)}I{el[t]blu",
        L"КоТэ С NoЖом",
        L"Adoranin",
        L"XoRoIIIuu",
        L"Har/la9IMopDa",
        L"Gangster",
        L"d3mOS?!JokerKannibal",
        L"Dameena",
        L"scoop",
        L"CeP6_MHe_kAk_D04b",
        L"Burgas",
        L"BTopIIIeHue_B_CPAkoTaH",
        L"Hurin",
        L"PASHA",
        L"Carmelo",
        L"H.u.LLl.T.9l.k",
        L"BupKub",
        L"Arador",
        L"splendidgamer",
        L"NightMaster",
        L"nikoNiNo",
        L"Пленник SexShop-а!",
        L"ne4eHbka`",
        L"OBIDA",
        L"14K-a-r-a-t*",
        L"Унитазная элементаль",
        L"AlvinRisk",
        L"malaDbIma",
        L"Кошка в вязаной шапке",
        L"Клавиатура Мониторовна",
        L"|>Fi'Ve",
        L"Adoraris",
        L"☜☢Legend☢☞",
        L"Jlblcblu4u6uc",
        L"Juce",
        L"mish@nya",
        L"Якудза",
        L"MasterJek",
        L"Fucking.Ba[nn]Y...«",
        L"Master_pvp",
        L"Сталин_каскадёр - =))",
        L"Memi",
        L"PetroSagaidachniy",
        L"}{олодный Πонос",
        L"MoJloDa9l_TIpukoJlucTka",
        L"Forcebrand",
        L"ПАСТУХ_МЕРТВЕЦОВ",
        L"Arilak",
        L"марионетка листопада",
        L"CrazyFedd",
        L"TPEHEP_B_TPYCAX",
        L"Frype",
        L"Сталин Арчер",
        L"yMHblu_koTe",
        L"777'''''''''''''rx",
        L"Rumpelshtinkel",
        L"Vse_niki_zanyaty",
        L"Bloodhammer",
        L"donkyHOT",
        L"FintitVitebsk",
        L"pe4enbka|:D",
        L"Alien",
        L"KIPISH",
        L"Gurisar",
        L"Толпа узкоглазых Якудза",
        L"Мама_сказала_тащи",
        L"Sleepy Lizard",
        L"RnD4ECHOK|onlyuspstylE:p",
        L"Старый_панда",
        L"Troll",
        L"MixFix",
        L"супер-пупер падла",
        L"Mira",
        L"Куропеко",
        L"Жжженя",
        L"ara_nsk_89reg(6bIJIou6bIJIo)",
        L"Marlboro",
        L"+Ak-47+",
        L"kollok(:",
        L"Дедушка-Западло",
        L"**TONY_13**",
        L"Romantico",
        L"bo0ne~",
        L"Luciferk@",
        L"naBJIuK_MoPo3oB",
        L"Nesquik*",
        L"DOLOR",
        L"kpuMuHaJl_off",
        L"anonymous",
        L"Kuladwyn",
        L"ITpocb6a_He_TblkaTb",
        L"★☆ВечНо_ПьянЫй☆★",
        L"Tor4oK",
        L"Hugira",
        L"DressingHerring",
        L"А вот и ЙА",
        L"~KaCnEpP*",
        L"ведь_были_крылья",
        L"Anton",
        L"kotIK",
        L"TRTR",
        L"Пенкуздуй",
        L"Pitstops",
        L"TPAXMECTEP",
        L"nOrMaLbNoDeLau'",
        L"ТэдЯ",
        L"TTEJlbMEHb",
        L"zolotoi",
        L"Подружка безопасности",
        L"furyy =**",
        L"GREeNday",
        L"nomerone",
        L">>AlMuslim",
        L"Chernik",
        L"Свинья Пеппа",
        L"Гусь Великий Воин",
        L"newr'''",
        L"Gralinda",
        L"нухотьэтотникблянезанят",
        L"Keralv",
        L"Fenrirr",
        L"Zeleniy_JIykgg",
        L"Hellconjuror",
        L"OcTpblu_Ha_9l3blk",
        L"☆k®aSi√@яЯ kAk zZ✔eZd@☆",
        L"71rus-rok-",
        L"Andromaginn",
        L"Zaletnyu",
        L"ParadoxalAnomality*KyKycuk",
        L"cAo'Record'sZASADABLYAT",
        L"САМ_ТАКОЙ",
        L".::PrOfeSaNaL::.",
        L"Ballistic",
        L"Дюжина_ножей_в_спину_революции",
        L"Dibei",
        L"CSDM.CsBlackDevil.Com",
        L"Mr.Gero1n",
        L"Oops1",
        L"Marsha",
        L"koHTakTHa9l",
        L"μεΔσςτγπμα ツ",
        L"Angle_fire",
        L"Malazar",
        L"70_JIeT_a_mo3ra_HeT",
        L"iSlate",
        L"whstyleawpforever)))",
        L"Smail-Bon",
        L"зачем_мне_ник",
        L"ky4kazombi",
        L"стремная гусеница",
        L"Adik_7sk",
        L"*G1O____________",
        L"cKuJl_B_Tpycax",
        L"Error parents",
        L"Bce_cHa4aJla_Ha4HeM",
        L"JoJok",
        L"Arihelm",
        L"danik*_*",
        L"Sabine",
        L"Mahmud(UKR)",
        L"Agamalore",
        L"FreshUp",
        L"kycok",
        L"XenoN",
        L"NeOn _DONI_ _ Mr.Dag_Marihuan4ik",
        L"yBeH4aHHblu_JlaBpaMu",
        L"Накуренный Волшебник",
        L"KJleBa9l_repJla",
        L"ЧинГачГук Обвислое Перо",
        L"CrazyBlackPlay",
        L"ОпАSнЫй ВоЗрАSт",
        L"Mill",
        L"babay",
        L"колючая карамелька",
        L"I7pocTo_HanpocTo",
        L"Ance",
        L"Пyk@N_в_огNe",
        L".::vohr::.",
        L"SkOrPiOnUs",
        L"NiggaBoss",
        L"Bandirdin",
        L"22-DiLLac",
        L"Ex1stence",
        L"Lamar",
        L"Torry",
        L"Mantrak(11rus)",
        L"СкОлЬзКаЯ МоЧаЛкА",
        L"i.l.y.a.35rys",
        L"Cookit:Freddiwe#",
        L"/IbICbIuKuHgep",
        L"Ichigo",
        L"The little black race",
        L"Опухший заяц",
        L"Beydar",
        L"nuBoCoC",
        L"lucky strike",
        L"HAXALL_nt",
        L"HOCOK_B_CMETAHE",
        L"Cordaath",
        L"burren",
        L"GooD FraG))",
        L"ghost_of fear",
        L"Explos!oN*_",
        L"волк_в_овечей_шкуре",
        L"He_TbIpb_Mou_gaMar",
        L"Hugintrius",
        L"Карманный Блоходав",
        L"GooDSpeeD",
        L"GyDrOpOn4iK",
        L"Alalay",
        L"Beast",
        L"vlad1k*",
        L"RodNou",
        L"WoT_Life_good",
        L"taganro:GRGR.Alien.",
        L"HanPuMeP",
        L"vjikBenQ",
        L"|GanIa|spb",
        L"NOoBOT",
        L"StAlexeya",
        L"Fani",
        L"100ReAln_TaTaRiN",
        L"BeTmAn",
        L"Sanelectrics",
        L"Bloodbrew",
        L"Vernon",
        L"mimic",
        L"Meshicage",
        L"Глиста в скафандре",
        L"БАБА С ВОЗУ",
        L"KPLy'",
        L"BeceJIbiuMoJIo4HukD",
        L"BigOS",
        L"TToJle3Hblu_urpok",
        L"34RUS",
        L"Bludmaster",
        L"Chilly-Willy",
        L"Daphine",
        L"NetsvobodnihNikoff",
        L"Head$hoTuku 0T AwoTuka",
        L"☞0tsosi ne trЯsi",
        L"IIIaman",
        L"reach beach",
        L"SuperDraigon",
        L"TTocJlegHuu_CaMypau",
        L"Modar",
        L"3JlaTuKTm|LeXa",
        L"Подметало",
        L"AIMaster",
        L"OleG@tOR*_*",
        L"scorpio",
        L"kotikvkedax",
        L"Arch3s",
        L"Kpaca_raJlJlakTuku",
        L"JaRViZZ",
        L"Why_always_me???",
        L"Алмазик",
        L"_____+_____!!!",
        L"ITcuX_YpABHoBeLLIeHHblu",
        L"Cka3o4Ha9l_TTepcoHa",
        L"CadBane",
        L"AnGeL",
        L"Melon",
        L"Paincliff",
        L"СвяТой_ТапоК",
        L"Vetal'",
        L"BJIacTeJIuH_KpeBeToK",
        L"Xlebyshik",
        L"Shooter",
        L"iBlackmine",
        L"Hammargren",
        L"Aleshia",
        L"Turan",
        L"kpenkuu4au",
        L"некропедозоофил",
        L"|Pi_Pi|",
        L"Schmille",
        L"Биссер",
        L"ЛblсоКоHb",
        L"Starrk",
        L"MaFro",
        L"Лысый аптекарь",
        L"PAPAN9",
        L"kirovski",
        L"kazah.SHIMKENT",
        L"Sharks|nyTEBbIu",
        L"d.S.q|>VIKING",
        L"Ляськи_Масяськи",
        L"Stafilak0k",
        L"FC747",
        L"Theend",
        L"QweRez",
        L"телаЧьи нежноСти",
        L"Ahieones",
        L"TAJMAHAL",
        L"Auridora",
        L"Тараканка",
        L"eBuRek",
        L"LEHUH_B_TAHKE",
        L"Краснопяточный грядкоторчатель",
        L"Sh0ker",
        L"The Best_Oloch",
        L"newlive",
        L"nedelia",
        L"дося",
        L"Доктор Зло - Аколит",
        L"Tpycbl_B_ropoLLIeK",
        L"Baton",
        L"3aMy4y_c_keM_3axo4y",
        L"azizpatron",
        L"TBOU_OJIENb",
        L"CJIoHuK",
        L"sasha.msk",
        L"Agatius",
        L"cTpaLLlHblu_TpoJlb",
        L"Durasell",
        L"mimimimimimim!",
        L"Домгагающаяся пандА",
        L"Brous",
        L"Sold",
        L"4m_skorIIuon",
        L"*****VITALIK*****11rus*",
        L"✪Ŧђє≈βøśś✪",
        L"=Vonuchk@228=",
        L"partizanekb",
        L"Thordifym",
        L"Landawyn",
        L"spinogryz",
        L"Burad",
        L"СЛЕГКА ОБДОЛБАНАЯ",
        L"Минздрав",
        L"`•.¸✿тβоя АդГﻉλ❍чKձ✿¸.•´",
        L"GreBBlY",
        L"*** ℳტᗫᎯℜტ ***",
        L"Darkfury",
        L"K@RM@",
        L"MUK@TNIYOPEWEK8659RU",
        L"Чудесный Хобот",
        L"Shelton",
        L"Инженер_Без_Манер",
        L"3oJloTou_TToDapok",
        L"Girmest",
        L"LLIkoJIoTa_Ha_KaHuKyJIaX",
        L"3a4apoBaHHa9l",
        L"Be4Ho_6yxou",
        L"Alsara",
        L"OgblH",
        L"Джафар с Востока",
        L"PTPPlayMan",
        L"legenda17",
        L"Skillet",
        L"Dairg",
        L"VorobeJ",
        L"Группа Крови",
        L"Cs-Fannat|Diamond",
        L"Круглый в карты проигрался",
        L"Это Был Не Нескафе",
        L"KoJlyM6uuckuu_6apoH",
        L"Триша",
        L"hOmE.cFg",
        L"GoMeR",
        L"Turg",
        L"Bonkers",
        L"Beabandis",
        L"Anen",
        L"~Planokyp~ALekcangp-",
        L"Only you"
    };

    static const int RANDOM_NICKNAMES_COUNT = sizeof(RANDOM_NICKNAMES) / sizeof(RANDOM_NICKNAMES[0]);

    // Функция для получения случайного имени из массива
    static wstring GetRandomNickname()
    {
      const int index = NRandom::Random(0, RANDOM_NICKNAMES_COUNT - 1);
      return wstring(RANDOM_NICKNAMES[index]);
    }
  }
}

